#*************Default eth0 Config **************#
mqprio_map0="0 2 1 2 3 4 5 6 2 3 4 5 1 2 3 6"
num_tc0=7
queue_map0="1@0 1@1 1@2 1@3 1@4 1@5 1@6"
q2_idle_slope0=100000
q2_send_slope0=-9900000
q2_hicredit0=77
q2_locredit0=-477056
q3_idle_slope0=100000
q3_send_slope0=-9900000
q3_hicredit0=77
q3_locredit0=-477056
q4_idle_slope0=0
q4_send_slope0=0
q4_hicredit0=0
q4_locredit0=0
q5_idle_slope0=0
q5_send_slope0=0
q5_hicredit0=0
q5_locredit0=0
q6_idle_slope0=0
q6_send_slope0=0
q6_hicredit0=0
q6_locredit0=0
mqprio_handle0=100
q2_cbs_handle0=200
q3_cbs_handle0=250
q4_cbs_handle0=255
q5_cbs_handle0=260
q6_cbs_handle0=265
q2_etf_handle0=275
q3_etf_handle0=300
tbs_enabled0=1
vlan0_id0=6
pcp0_value0=5
skb0_priority0=7
vlan1_id0=7
pcp1_value0=6
skb1_priority0="b"
vlan2_id0=9
pcp2_value0=3
skb2_priority0=2
eavb_vlan_id0=2
protocol0=""
l4_port0=5060
l3_ip_address0=""
is_src0=0
q2_delta0=300000
q3_delta0=300000

#*************Default eth1 Config **************#
mqprio_map1="0 2 1 2 3 4 5 6 2 3 4 5 1 2 3 6"
num_tc1=7
queue_map1="1@0 1@1 1@2 1@3 1@4 1@5 1@6"
q2_idle_slope1=100000
q2_send_slope1=-9900000
q2_hicredit1=77
q2_locredit1=-477056
q3_idle_slope1=100000
q3_send_slope1=-9900000
q3_hicredit1=77
q3_locredit1=-477056
q4_idle_slope1=0
q4_send_slope1=0
q4_hicredit1=0
q4_locredit1=0
q5_idle_slope1=0
q5_send_slope1=0
q5_hicredit1=0
q5_locredit1=0
q6_idle_slope1=0
q6_send_slope1=0
q6_hicredit1=0
q6_locredit1=0
mqprio_handle1=400
q2_cbs_handle1=500
q3_cbs_handle1=550
q4_cbs_handle1=555
q5_cbs_handle1=560
q6_cbs_handle1=565
q2_etf_handle1=575
q3_etf_handle1=600
tbs_enabled1=1
vlan0_id1=6
pcp0_value1=5
skb0_priority1=7
vlan1_id1=7
pcp1_value1=6
skb1_priority1="b"
vlan2_id1=9
pcp2_value1=3
skb2_priority1=2
eavb_vlan_id1=2
protocol1=""
l4_port1=5060
l3_ip_address1=""
is_src1=0
q2_delta1=300000
q3_delta1=300000
