# net.conf - tmpfiles rules for setup-qos
#
# This rule adjusts ownership/permissions of eth0's RPS control file so that
# the 'setup-qos' service can configure Receive Packet Steering (RPS) on
# eth0 RX queue 0 (rps_cpus). The actual RPS value is written by setup_eth.sh
# at runtime.
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

z /sys/class/net/eth0/queues/rx-0/rps_cpus 0664 root setup-qos -
