require conf/machine/sa8797.conf

# We are planning to migrate machine to gen5, set PRODUCT to sa8797 here
# to be compatible with current image path and flash command, will update
# once new machine migration done.
PRODUCT = "sa8797"
