# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

[Unit]
After        = sleep-apps.target
Requires     = sleep-apps.target

Before       = sleep-drivers.target
PartOf       = sleep-drivers.target

[Service]
ExecStopPost = systemctl start gles2_kpi

[Install]
RequiredBy   = sleep-drivers.target
